### ISSUE TITLE
Start error on `unknown locale: UTF-8`

### ISSUE THREAD

**Issue by liweijian** [jeetsukumaran/Syrupy#9]
I installed syrupy by 
>  sudo python setup.py install

However, when I started the program, there's an error as
```bash
syrupy.py -p 548    
Traceback (most recent call last):
  File "/usr/local/bin/syrupy.py", line 4, in <module>
    __import__('pkg_resources').run_script('Syrupy==1.4.0', 'syrupy.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/Syrupy-1.4.0-py2.7.egg/EGG-INFO/scripts/syrupy.py", line 39, in <module>

  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by liweijian** [comment]
Sorry, I got the [answer](http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8) right now:)
